name: Deployment

on:
  create:
  workflow_dispatch:

jobs:
  deploy-component:
    name: Deploy Component
    runs-on: ubuntu-20.04
    env:
      KUBE_TOKEN: ${{ secrets.ABLE_KUBE_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.ABLE_KUBE_CONFIG_DATA}}
      KUBECONFIG: /tmp/kube-config
      ECR_REPOSITORY: platform
      IMAGE_TAG: ${{ github.sha }}
      AWS_REGION: us-east-1
      AWS_CERTIFICATE_ARN: ${{ secrets.ABLE_AWS_CERTIFICATE_ARN }}
      PLATFORM_APP_NAME: ${{ github.event.repository.name }}
      PLATFORM_DB_PASSWORD: ${{ secrets.PLATFORM_DB_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - name: Get Database name
        run: echo PLATFORM_DB_NAME=$(echo $PLATFORM_APP_NAME | tr '-' '_') >> $GITHUB_ENV
      - name: Create new database
        run: |
          PGPASSWORD=${{ secrets.RDS_MASTER_PASSWORD }} psql -U root -h terraform-20210802015341504500000002.cvvdjoavecoc.us-east-1.rds.amazonaws.com platform -c "drop database if exists $PLATFORM_DB_NAME"
          PGPASSWORD=${{ secrets.RDS_MASTER_PASSWORD }} psql -U root -h terraform-20210802015341504500000002.cvvdjoavecoc.us-east-1.rds.amazonaws.com platform -c "create database $PLATFORM_DB_NAME"
          PGPASSWORD=${{ secrets.RDS_MASTER_PASSWORD }} psql -U root -h terraform-20210802015341504500000002.cvvdjoavecoc.us-east-1.rds.amazonaws.com platform -c "create user $PLATFORM_DB_NAME with encrypted password '$PLATFORM_DB_PASSWORD'"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ABLE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ABLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build \
            -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
      - name: Set cluster configuration
        run: |
          echo "$KUBE_CONFIG_DATA" | base64 -d > /tmp/kube-config
          chmod 600 /tmp/kube-config
      - name: Run helm
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          AWS_CERTIFICATE_ARN: ${{ secrets.AWS_CERTIFICATE_ARN }}
          GOOGLE_CLIENT_ID: ${{ secrets.PLATFORM_GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.PLATFORM_GOOGLE_CLIENT_SECRET }}
          SESSION_SECRET_KEY: ${{ secrets.PLATFORM_SESSION_SECRET_KEY }}
          GOOGLE_CALLBACK_URL: https://oauth-proxy.able.co
          DATABASE_URL: doable_app_repo_name:doable_app_repo_name@terraform-20210802015341504500000002.cvvdjoavecoc.us-east-1.rds.amazonaws.com:doable_app_repo_name
        run: |
          helm upgrade --wait --install $PLATFORM_APP_NAME component \
            --namespace platform \
            --set image.repository=$ECR_REGISTRY/$ECR_REPOSITORY \
            --set image.tag=$IMAGE_TAG \
            --set ingress.alb.certificateArn=$AWS_CERTIFICATE_ARN \
            --set env.database_url=$DATABASE_URL \
            --set env.session_secret_key=$SESSION_SECRET_KEY \
            --set env.google_client_id=$GOOGLE_CLIENT_ID \
            --set env.google_client_secret=$GOOGLE_CLIENT_SECRET \
            --set env.google_callback_url=$GOOGLE_CALLBACK_URL \
            --kube-token $KUBE_TOKEN
        working-directory: helm
