name: Deployment

on:
  create:
  workflow_dispatch:

jobs:
  deploy-component:
    name: Deploy Component
    runs-on: ubuntu-20.04
    env:
      KUBE_TOKEN: ${{ secrets.ABLE_KUBE_TOKEN }}
      KUBE_CONFIG_DATA: ${{ secrets.ABLE_KUBE_CONFIG_DATA}}
      KUBECONFIG: /tmp/kube-config
      ECR_REPOSITORY: platform
      IMAGE_TAG: ${{ github.sha }}
      AWS_REGION: us-east-1
      AWS_CERTIFICATE_ARN: ${{ secrets.ABLE_AWS_CERTIFICATE_ARN }}

    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ABLE }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ABLE }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
